---
- hosts: all
  become: yes
  tasks:
    - name: Update 
      apt:
        update_cache: yes
    - name: Install Apache HTTP server (httpd)
      apt:
        name: apache2  
        state: present
      notify: start httpd

  handlers:
    - name: start httpd
      service:
        name: apache2  
        state: started

